### ISSUE TITLE
How to failover when Artifact is not found

### ISSUE THREAD

**Issue by dadpig** [devopshq/artifactory-cleanup#123]
Hello guys, I need help, is there any parameter so that when the artifact selected by the policy is not found, the cleaning does not abort? I am running with the following parameters:

docker run --rm -v /mnt/workspace/test-artifactory-cleanup:/app -e ARTIFACTORY_USERNAME -e ARTIFACTORY_PASSWORD devopshq/artifactory-cleanup:1.0.8 artifactory-cleanup --destroy

```
artifactory-cleanup:
  server: https://artifactory.internal.com/artifactory
  #  is auto populated from environment variables
  user: artifactorycleaner
  password: ****

  policies:
    - name: DeleteNotUsedSince from snapshot older than 2100 days
      rules:
        - rule: Repo
          name: "snapshot"
        - rule: DeleteNotUsedSince
          days: 2100
```

```
Traceback (most recent call last):
  File "/usr/local/bin/artifactory-cleanup", line 8, in <module>
    sys.exit(ArtifactoryCleanupCLI())
  File "/usr/local/lib/python3.9/site-packages/plumbum/cli/application.py", line 177, in __new__
    return cls.run()
  File "/usr/local/lib/python3.9/site-packages/plumbum/cli/application.py", line 633, in run
    retcode = inst.main(*tailargs)
  File "/usr/local/lib/python3.9/site-packages/artifactory_cleanup/cli.py", line 164, in main
    for summary in cleanup.cleanup(
  File "/usr/local/lib/python3.9/site-packages/artifactory_cleanup/artifactorycleanup.py", line 59, in cleanup
    policy.delete(artifact, destroy=self.destroy)
  File "/usr/local/lib/python3.9/site-packages/artifactory_cleanup/rules/base.py", line 313, in delete
    r.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://artifactory/snapshot/com/csi/services/3.135.0-SNAPSHOT/maven-metadata.xml
```

**Comment by allburov** [comment]
Hi! 
The main question - why did it find the artifact? May be it's been deleted by another policy or some conflicts found?
For internal files like maven metadata it's better to filter out them and remove only the actual package - artifactory must handle it automatically (as I remember)

No easy solution yet, but I'd find the root cause of it - the script SAW the artifact, but it disappeared after filtering - it can be a sign of some error in the configuration

**Comment by Rommmmm** [comment]
Hey,
Just throwing an idea here, maybe we need ignore failure option?

**Comment by dadpig** [comment]
Yeah I just encapsulated this call in a try catch and, whenever the not found exception arises just log it in the console. Cause if I was trying to exclude something that was already removed I don’t consider it as Failure and don’t want to interrupt the cleaning process. 

I created a new parameter on my side for this failover behavior on command line.

**Comment by Rommmmm** [comment]
maybe create a PR so people can enjoy your improvement?

**Comment by allburov** [comment]
> maybe create a PR so people can enjoy your improvement?
@Rommmmm @dadpig 
It'd be great!

**Comment by Rommmmm** [comment]
> > maybe create a PR so people can enjoy your improvement?
> 
> @Rommmmm @dadpig It'd be great!

I have PR ready to ignore not-found and also i added threads flag, when trying to create im getting 403 do i need to get some permissions or something?

**Comment by allburov** [comment]
@Rommmmm where is the PR exactly? I don't see it here https://github.com/devopshq/artifactory-cleanup/pulls

**Comment by Rommmmm** [comment]
Getting 403 when pushing my branch

Sincerely,
Roman Roberman

**Comment by Rommmmm** [comment]
@allburov 
https://github.com/devopshq/artifactory-cleanup/pull/127
