### ISSUE TITLE
check method is a conflict in IncludeDockerImages rule

### ISSUE THREAD

**Issue by zhan9san** [devopshq/artifactory-cleanup#133]
There would be an error if colon is not defined in `IncludeDockerImages`'s `masks`.

The check method in `IncludeDockerImages` is redundant.  because the colon would be replaced in https://github.com/devopshq/artifactory-cleanup/blob/b461468ef034f02669f17f3c2adbced8965b6e6d/artifactory_cleanup/rules/docker.py#L159-L161

IMHO, there is no need to do check. The following two cases should work, but currently only the first one work.

Work:

```txt
        - rule: IncludeDockerImages
          masks: foo:*
```

Does not work

```txt
        - rule: IncludeDockerImages
          masks: foo*
```

BTW, there is no colon in the example in README 
https://github.com/devopshq/artifactory-cleanup/blob/b461468ef034f02669f17f3c2adbced8965b6e6d/README.md?plain=1#L315-L333

**Comment by allburov** [comment]
The fix released in `1.0.9`
