### ISSUE TITLE
Question: plan to release on Pypi ?

### ISSUE THREAD

**Issue by Lucas-C** [devopshq/artifactory-cleanup#15]
Hello !

In your [installation steps](https://github.com/devopshq/artifactory-cleanup#install), you suggest to install this tool from Pypi.

However it does not seem to published there yet : https://pypi.org/project/artifactory-cleanup/

Do you plan on releasing it soon ? :)

**Comment by nikolasj** [comment]
Hello ! Yes. We will do it soon

**Comment by allburov** [comment]
Probably, we should remove this section and add "How to install from git-repo"

**Comment by Tim55667757** [comment]
We will try to make a package for this api. We plans it. I will not promise but for sure this year :) Thanks for your understanding!

**Comment by allburov** [comment]
I've removed any mentioning about PyPI from readme.md. It was confusing a little.
