### ISSUE TITLE
Upload artifactory-cleanup to Pypi

### ISSUE THREAD

**Issue by zhan9san** [devopshq/artifactory-cleanup#23]
Hi,
I appreciate you have created a great project. It satisfies our cleanup requirement.

Do we have a plan to upload this package to Pypi?

Here is one scenario.
A remote repository Pypi is set up in Artifactory.
I'd like to install this package in internal network.

I know we could workaround in many ways, like packaging it in Container or uploading it in local repository.

**Comment by zhan9san** [comment]
Besides, once it is uploaded to Pypi, accordingly, there will be one specific version, and then users can install specific version.

**Comment by martinm82** [comment]
I started with a first step (#28 ) and have a GH workflow in place which can later be extended to publish to pypi.org.

**Comment by DrackThor** [comment]
Hello, is there any progress on this topic?
Would be awesome to find this tool on pypi as well!

**Comment by allburov** [comment]
Hi! I've deployed a pypi package for the project https://pypi.org/project/artifactory-cleanup/
Every commit in `master` branch triggers deploy to pypi https://github.com/devopshq/artifactory-cleanup/blob/master/.github/workflows/deploy.yml
