### ISSUE TITLE
where do we need to run the command ?

### ISSUE THREAD

**Issue by vijay-Jonathan** [devopshq/artifactory-cleanup#29]
Hi, I'm new to this artifactory, 
I'm using windows os and when I try to run the command it shows
 _artifactory-cleanup: The term 'artifactory-cleanup' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again._

Plz help me

**Comment by rockdreamer** [comment]
Hi vijay, please familiarise yourself with python virtual environments before asking for support on this. Google is your friend.
You need to create a python virtualenv, activate it and follow the instructions in the readme file to install artifactory-cleanup.
