### ISSUE TITLE
Stabilize and document API for Rules

### ISSUE THREAD

**Issue by rockdreamer** [devopshq/artifactory-cleanup#33]
Hi, I followed the existing rules in the codebase and created a rather convoluted one for my company's requirements. It's working quite well but I'd like to have an API that is documented and reasonably stable and some unit testing in place.

Is this a direction you're interested in for this project?

**Comment by allburov** [comment]
@rockdreamer Hi! Are you talking about more stable API for rules in the library? 
The library has quite stable API (but not documented well), so you can rely on it
