### ISSUE TITLE
CI pipeline branching strategy

### ISSUE THREAD

**Issue by DrackThor** [devopshq/artifactory-cleanup#34]
Hi guys,

is it possible to trigger the Pypi publish pipeline only when a new Release is created?
That way we could make sure to only release to pypi when a new release is created.
Therefore we could add multiple features (aka PRs to master) within one release and only published the finished thing.

**Comment by allburov** [comment]
I think https://github.com/devopshq/artifactory-cleanup/pull/46 will fix the issue
