### ISSUE TITLE
Can I use this tools on JCR ?

### ISSUE THREAD

**Issue by risingwen** [devopshq/artifactory-cleanup#59]
Thank you for your awesome tool!

**Comment by donhui** [comment]
After testing, I found that there was a problem. It failed with an exceptions:
`
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://jcr.xxx.com/artifactory/api/search/aql
`

In `artifactory-service.log`, the error as follows:
`2022-08-27T13:02:37.012Z [jfrt ] [ERROR] [4ed166efe9b7ce9a] [o.a.r.r.a.AqlResource:102     ] [http-nio-8081-exec-1] - Fail to execute query: items.find({"$and": [{"repo": {"$match": "docker-test"}}, {"modified": {"$lt": "2022-08-17"}, "name": {"$match": "manifest.json"}}]}).include("*", "property", "stat").sort({"$asc" : ["created"]}): Sorting is not supported by AQL in the open source version
`

**Comment by allburov** [comment]
Hi! 
@donhui did you tested with `KeepLatestNFiles` rule? I see the only place where we're using `sort` - it's that rule.
We can remove that part and use in-memory sorting, it should be fine

@risingwen it's better to test it with your case. As long as JCR support AQL and DELETE API method - it works with artifactory-cleanup tool!

**Comment by donhui** [comment]
@allburov 
I tested with `keep_latest_n_file_in_folder` rule. 
There are no problems with other rules for JCR.
