### ISSUE TITLE
how to trust certificate?

### ISSUE THREAD

**Issue by jetersen** [devopshq/artifactory-cleanup#6]
need a way to add custom certificates.

**Comment by casz** [comment]
hmm digging back into python I may have found a better way to include the certificate:

Written for python 3

```python
import requests
import certifi
import sys

try:
    requests.get('https://artifactory.company.com')
    print('Certificate already added to the certifi store')
    sys.exit(0)
except requests.exceptions.SSLError as err:
    print('SSL Error. Adding custom certs to Certifi store...')
    customca = requests.get('http://certificates.company.com/root-ca.pem').content
    cafile = certifi.where()
    with open(cafile, 'ab') as outfile:
        outfile.write(b'\n')
        outfile.write(customca)

try:
    requests.get('https://artifactory.company.com')
    print('Successfully added 3Shape certificate to the certifi store')
    sys.exit(0)
except requests.exceptions.SSLError as err:
    print('Failed to add 3Shape certificate to the certifi store')
    sys.exit(1)

```

**Comment by casz** [comment]
hmm digging back into python I may have found a better way to include the certificate:

Written for python 3

```python
import requests
import certifi
import sys

try:
    requests.get('https://artifactory.company.com')
    print('Certificate already added to the certifi store')
    sys.exit(0)
except requests.exceptions.SSLError as err:
    print('SSL Error. Adding custom certs to Certifi store...')
    customca = requests.get('http://certificates.company.com/root-ca.pem').content
    cafile = certifi.where()
    with open(cafile, 'ab') as outfile:
        outfile.write(b'\n')
        outfile.write(customca)

try:
    requests.get('https://artifactory.company.com')
    print('Successfully added certificate to the certifi store')
    sys.exit(0)
except requests.exceptions.SSLError as err:
    print('Failed to add certificate to the certifi store')
    sys.exit(1)

```

**Comment by TJM** [comment]
Trusting the certificate for your artifactory at the "system" level seems like the most straightforward approach. (besides obtaining a properly signed cert)

**Comment by DrackThor** [comment]
I always make use of the "[REQUESTS_CA_BUNDLE](https://2.python-requests.org/en/master/user/advanced/#verification)" environment variable.
Just add your custom CA cert to your system wide trusted certs and point REQUESTS_CA_BUNDLE to this file.
E.g:
```
cp my-ca.crt /usr/local/share/ca-certificates/
chmod 644 /usr/local/share/ca-certificates/my-ca.crt && update-ca-certificates
export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
```

**Comment by allburov** [comment]
@TJM does the solution above help you?

**Comment by TJM** [comment]
@allburov our Artifactory is used for "docker" and without having to modify the kubernetes worker nodes to trust some internal CA, we chose to get a publicly signed wildcard cert for our internal Artifactory server (uses a public domain name, but internal only). As such, I was just making a suggestion for the other people that were affected. Trusting the cert at the system level still seems like the easiest approach. That appears to be what @DrackThor is suggesting above.

**Comment by allburov** [comment]
@TJM tricky solution! 
Great, we may add the system level cert solution to the FAQ section

**Comment by allburov** [comment]
https://github.com/devopshq/artifactory-cleanup#how-to-connect-self-signed-certificates-for-docker
