### ISSUE TITLE
TeamCity messages should only be activated if running on TeamCity.

### ISSUE THREAD

**Issue by jetersen** [devopshq/artifactory-cleanup#7]
You could use `TEAMCITY_VERSION` to detect when running on teamcity.

**Comment by TJM** [comment]
On one hand, I agree with you, as the messages are a little strange, but on the other, they are really just timestamp'd log messages... I don't use TeamCity (nor have I ever), but I even added some of the "TC" blocks just so I could get timing on some "features" to track down what was taking soo long.
