### ISSUE TITLE
How to set retention policy in jfrog Artifactory

### ISSUE THREAD

**Issue by vivuu1989** [devopshq/artifactory-cleanup#95]
Looking for a way to set retention period in JFrog antifactory, which will remove SNAPSHOT versions older than 100 days.

If any teams need particular files need to be keep in artifactory for ever, need to exclude some path alone in that repo from retention policy and other directories should be removed as per the retention policy.

**Comment by allburov** [comment]
Please get familiar with the tool first, try to play with it and ask detailed questions if you have any
https://github.com/devopshq/artifactory-cleanup#readme

The best way to filter artifacts - move them from snapshot repository to some sort of "release" repository where no policy applied. So you just need to apply DeleteOlderThan + Repo rules in a cleanup policy

Another way is to exclude them by a property with PropertyNeq rule, like `keepForever: true`
